export const INCREMENT_HEROHP = 'INCREMENT_HEROHP';
export type INCREMENT_HEROHP = typeof INCREMENT_HEROHP;


export const DECREMENT_HEROHP = 'DECREMENT_HEROHP';
export type DECREMENT_HEROHP = typeof DECREMENT_HEROHP;

